/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-qo100_modem
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_QO100_MODEM_API_H
#define INCLUDED_QO100_MODEM_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_qo100_modem_EXPORTS
#define QO100_MODEM_API __GR_ATTR_EXPORT
#else
#define QO100_MODEM_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_QO100_MODEM_API_H */
